# Site settings
# You can customize these values later

# Site title
title: "Jennifer Wang"
# Site description
description: "Personal website of Jennifer Wang"
# Base URL
baseurl: ""
# URL
url: "https://wangjenn.github.io"
# Markdown processor
markdown: kramdown
# Theme (leave blank for custom layout)
theme: null
